<template>
  <view class="analyze-page">
    <template v-if="completed"><view class="complete-mark">✓</view><view class="page-title complete-title">今日训练完成</view><view class="complete-copy">你留下了一个结构判断、一段短作答和一个可迁移表达。</view><view class="card deposit-card"><view class="card-desc">今日表达</view><view class="card-title">{{ deposit }}</view></view><button class="auth-button" @tap="home">返回今日</button></template>
    <template v-else-if="feedbackReady"><view class="eyebrow">规则反馈 · 已同步训练记录</view><view class="page-title">先看失分点，再结束训练</view><view class="feedback-score"><view class="score-number">{{ feedback.score }}</view><view><view class="card-title">规则完成度</view><view class="card-desc">这是结构化规则反馈，不替代人工阅卷分数。</view></view></view>
      <view v-for="item in feedback.items" :key="item.key" class="card feedback-item"><view class="feedback-status" :class="{ weak: !item.passed }">{{ item.passed ? '达成' : '待改进' }}</view><view><view class="card-title">{{ item.title }}</view><view class="card-desc">{{ item.note }}</view></view></view>
      <view class="section-head"><view class="section-title">本次主要失分原因</view><view class="section-meta">选 1 项</view></view><view class="reason-grid"><view v-for="reason in reasons" :key="reason" class="reason-chip" :class="{ selected: weakReason === reason }" @tap="weakReason=reason">{{ reason }}</view></view>
      <view class="card rewrite-card"><view class="card-title">下一次只改这一点</view><view class="card-desc">{{ improvement }}</view></view><button class="auth-button submit-training" :disabled="!weakReason || submitting" @tap="confirmFeedback">确认复盘并完成</button>
    </template>
    <template v-else><view class="eyebrow">{{ articleTitle }}</view><view class="page-title">三刀拆开，再主动输出</view><view class="analyze-tip">内容自动保存在本机，提交后同步到开采本。</view>
      <view class="section-head"><view class="section-title">第一刀 · 立意</view><view class="section-meta">文章解决什么问题</view></view><textarea v-model="thesis" class="analyze-input" maxlength="300" placeholder="用自己的话写出核心问题与主张" />
      <view class="section-head"><view class="section-title">第二刀 · 结构</view><view class="section-meta">观点如何展开</view></view><textarea v-model="structure" class="analyze-input" maxlength="500" placeholder="梳理总论点、分论点和论证关系" />
      <view class="section-head"><view class="section-title">第三刀 · 表达</view><view class="section-meta">哪些写法可迁移</view></view><textarea v-model="expression" class="analyze-input" maxlength="300" placeholder="摘取并解释一个规范表达或句式" />
      <view class="section-head"><view class="section-title">120 字短作答</view><view class="section-meta">{{ answer.length }} / 120</view></view><textarea v-model="answer" class="analyze-input answer-input" maxlength="120" placeholder="概括文章关注的核心问题与主要解决思路" />
      <view class="section-head"><view class="section-title">表达沉淀</view><view class="section-meta">只留一个</view></view><input v-model="deposit" class="auth-input deposit-input" maxlength="40" placeholder="今天最值得带走的规范表达" />
      <button class="auth-button submit-training" :disabled="submitting" @tap="submit">{{ submitting ? '正在分析…' : '提交并查看规则反馈' }}</button>
    </template>
  </view>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import Taro, { useRouter } from '@tarojs/taro'
import { api } from '@/api'
import { useDailyTaskStore } from '@/store/dailyTask'
import { showToast } from '@/utils/platform'

const router=useRouter(); const store=useDailyTaskStore(); const articleId=String(router.params?.articleId||''); const rawTitle=String(router.params?.title||'申论精读'); const articleTitle=decodeURIComponent(rawTitle); const taskId=String(router.params?.taskId||'');
interface FeedbackItem { key:string; title:string; passed:boolean; note:string }
const thesis=ref(''); const structure=ref(''); const expression=ref(''); const answer=ref(''); const deposit=ref(''); const submitting=ref(false); const completed=ref(false); const feedbackReady=ref(false); const weakReason=ref(''); const storageKey=`shenlun-analyze:${articleId}`
const reasons=['要点遗漏','对象不清','层次混乱','表述不规范','字数失控']
const feedback=computed(()=>{const text=answer.value.replace(/\s/g,'');const hasObject=/群众|基层|企业|政府|部门|社会|文章|问题|治理|发展/.test(text);const hasLayers=/(一是|二是|首先|其次|同时|；)/.test(text);const hasActions=/(加强|完善|推动|建立|提升|优化|健全|促进|强化)/.test(text);const lengthOk=text.length>=60&&text.length<=120;const items:FeedbackItem[]=[{key:'length',title:'字数与完整度',passed:lengthOk,note:lengthOk?'篇幅适中，具备完整表达空间。':'建议控制在 60—120 字，避免过短漏点。'},{key:'object',title:'对象与主题',passed:hasObject,note:hasObject?'答案中出现了明确对象或治理主题。':'开头先交代概括对象，避免答案悬空。'},{key:'layers',title:'要点层次',passed:hasLayers,note:hasLayers?'已使用分层词或分号组织要点。':'用“一是、二是”或分号拆分不同要点。'},{key:'action',title:'规范动词',passed:hasActions,note:hasActions?'使用了申论常见规范动词。':'把口语表达改为完善、健全、推动、强化等动作。'}];return {items,score:items.filter(item=>item.passed).length*25}})
const improvement=computed(()=>({要点遗漏:'回到材料按主体圈出动作，每个主体至少保留一个有效要点。',对象不清:'第一句话先写清“谁、围绕什么问题”，再列举表现或做法。',层次混乱:'同类项合并、异类项分开，用“一是、二是”形成可阅卷层次。',表述不规范:'删除口语和情绪词，优先使用材料中的规范名词与动作。',字数失控:'先列关键词再成句，保留对象、核心动作和结果，删除解释性重复。'}[weakReason.value]||'选择一个主要失分原因，形成下一次训练的单点目标。'))
function snapshot(){return {thesis:thesis.value,structure:structure.value,expression:expression.value,answer:answer.value,deposit:deposit.value}}
watch([thesis,structure,expression,answer,deposit],()=>Taro.setStorageSync(storageKey,snapshot()))
onMounted(async()=>{const cached=Taro.getStorageSync(storageKey)||{};thesis.value=cached.thesis||'';structure.value=cached.structure||'';expression.value=cached.expression||'';answer.value=cached.answer||'';deposit.value=cached.deposit||'';if(taskId&&!store.task)await store.load();if(store.task?.progress.state==='submitted'||store.task?.progress.state==='reviewed'){const draft=store.task.progress.draft||{};thesis.value=String(draft.thesis||thesis.value);structure.value=String(draft.structure||structure.value);expression.value=String(draft.expression||expression.value);answer.value=String(draft.answer||answer.value);deposit.value=String(draft.deposit||deposit.value);weakReason.value=String(draft.weakReason||'');feedbackReady.value=true}else if(store.task?.progress.state==='completed')completed.value=true})
async function submit(){if(!thesis.value.trim()||!structure.value.trim()||!expression.value.trim())return showToast('请完成三刀拆解');if(answer.value.trim().length<30)return showToast('短作答至少写 30 字');if(!deposit.value.trim())return showToast('请留下一个规范表达');submitting.value=true;const draft={...snapshot(),feedback:feedback.value};const mine=await api.saveMine({articleId,articleTitle,sourceExcerpt:thesis.value,argumentChain:structure.value,templateSentence:expression.value,terms:[deposit.value.trim()]});if(mine.code!==0||!mine.data){submitting.value=false;return showToast(mine.message||'开采本保存失败')}const drill=await api.addDrill({drillType:'sentence',content:answer.value.trim(),prompt:`${articleTitle}｜规则完成度 ${feedback.value.score} 分`,refMineId:mine.data.id});if(drill.code!==0){submitting.value=false;return showToast(drill.message||'训练记录保存失败')}if(taskId&&store.task?.id===taskId&&store.task.progress.state==='in_progress'){const ok=await store.transition('save',draft,3)&&await store.transition('submit',draft,4);if(!ok){submitting.value=false;return showToast(store.message||'任务进度同步失败')}}submitting.value=false;feedbackReady.value=true}
async function confirmFeedback(){if(!weakReason.value)return showToast('请选择一个主要失分原因');submitting.value=true;if(taskId&&store.task?.id===taskId){const draft={...store.task.progress.draft,weakReason:weakReason.value,improvement:improvement.value};let ok=true;if(store.task.progress.state==='submitted')ok=await store.transition('review',draft,4);if(ok&&store.task?.progress.state==='reviewed')ok=await store.transition('complete',draft,4);if(!ok){submitting.value=false;return showToast(store.message||'复盘保存失败')}}Taro.removeStorageSync(storageKey);submitting.value=false;feedbackReady.value=false;completed.value=true}
function home(){Taro.switchTab({url:'/pages/today/index'})}
</script>
