"""RBAC 权限码定义"""

PERMISSIONS = {
    "article:read": "查看文章",
    "article:write": "管理文章",
    "question:read": "查看试题",
    "question:write": "管理试题",
    "user:read": "查看用户",
    "user:write": "管理用户",
    "setting:read": "查看系统设置",
    "setting:write": "管理系统设置",
    "crawler:read": "查看爬虫日志",
    "crawler:run": "执行爬虫",
    "admin:read": "查看管理员",
    "admin:write": "管理管理员与角色",
    "knowledge:read": "查看知识框架",
    "knowledge:write": "管理知识框架",
    "plan:read": "查看学习计划模板",
    "plan:write": "管理学习计划模板",
    "exam:read": "查看试卷题库",
    "exam:write": "管理试卷题库",
    "english:read": "查看英语内容",
    "english:write": "管理英语内容",
    "ziliao:read": "查看资料分析内容",
    "ziliao:write": "管理资料分析内容",
    "rmrb:read": "查看人民日报模块",
    "rmrb:write": "管理人民日报模块",
    "corpus:read": "查看语料本",
    "corpus:write": "管理语料本",
    "events:read": "查看时事事件",
    "events:write": "管理时事事件",
    "health:read": "查看健康数据",
    "health:write": "管理健康数据",
    "dushu:read": "查看读书内容",
    "dushu:write": "管理读书内容",
}

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": list(PERMISSIONS.keys()),
    "editor": [
        "article:read",
        "article:write",
        "question:read",
        "question:write",
        "crawler:read",
        "crawler:run",
        "user:read",
        "knowledge:read",
        "knowledge:write",
        "plan:read",
        "plan:write",
        "exam:read",
        "exam:write",
        "english:read",
        "english:write",
        "ziliao:read",
        "ziliao:write",
        "rmrb:read",
        "rmrb:write",
        "corpus:read",
        "corpus:write",
        "events:read",
        "events:write",
        "health:read",
        "health:write",
        "dushu:read",
        "dushu:write",
    ],
    "viewer": [
        "article:read",
        "question:read",
        "user:read",
        "crawler:read",
        "setting:read",
        "knowledge:read",
        "plan:read",
        "exam:read",
        "english:read",
        "ziliao:read",
        "rmrb:read",
        "corpus:read",
        "events:read",
        "health:read",
        "dushu:read",
    ],
}


def role_has_permission(role_code: str, permission: str) -> bool:
    perms = ROLE_PERMISSIONS.get(role_code, [])
    return permission in perms or role_code == "super_admin"
