export default defineAppConfig({
  pages: [
    'pages/auth/login',
    'pages/auth/register',
    'pages/today/index',
    'pages/index/index',
    'pages/article/detail',
    'pages/article/mindmap',
    'pages/question/index',
    'pages/question/taking',
    'pages/question/article-pick',
    'pages/question/review',
    'pages/question/wrong',
    'pages/question/manual-list',
    'pages/question/manual-quiz',
    'pages/question/manual-edit',
    'pages/user/index',
    'pages/user/profile',
    'pages/user/signin',
    'pages/user/points',
    'pages/user/rank',
    'pages/user/growth',
    'pages/user/feedback',
    'pages/corpus/index',
    'pages/corpus/edit',
    'pages/plan/today',
    'pages/plan/review',
    'pages/plan/week',
    'pages/plan/day',
    'pages/knowledge/index',
    'pages/events/index',
    'pages/events/edit',
    'pages/review/hub',
    'pages/review/quiz',
    'pages/exam/list',
    'pages/exam/detail',
    'pages/exam/taking',
    'pages/exam/result',
    'pages/ziliao/index',
    'pages/ziliao/formulas',
    'pages/ziliao/formula-detail',
    'pages/ziliao/types',
    'pages/ziliao/type-detail',
    'pages/ziliao/tricks',
    'pages/ziliao/trick-detail',
    'pages/ziliao/drill',
    'pages/ziliao/result',
    'pages/rmrb/index',
    'pages/rmrb/article-list',
    'pages/rmrb/article-detail',
    'pages/rmrb/mines',
    'pages/rmrb/mine-edit',
    'pages/rmrb/terms',
    'pages/rmrb/drill',
  ],
  window: {
    navigationBarBackgroundColor: '#1E3A5F',
    navigationBarTitleText: '知行公考',
    navigationBarTextStyle: 'white',
    backgroundColor: '#F3F4F6',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#1E3A5F',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      // H5 开发态会误删 iconPath 首字符（assets → ssets），必须写 ./ 前缀；
      // 生产构建会自动改写并打包到 /static/images/*.png
      {
        pagePath: 'pages/today/index',
        text: '今日',
        iconPath: './assets/icons/today.png',
        selectedIconPath: './assets/icons/today-active.png',
      },
      {
        pagePath: 'pages/index/index',
        text: '学习',
        iconPath: './assets/icons/home.png',
        selectedIconPath: './assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/question/index',
        text: '练习',
        iconPath: './assets/icons/quiz.png',
        selectedIconPath: './assets/icons/quiz-active.png',
      },
      {
        pagePath: 'pages/user/index',
        text: '我的',
        iconPath: './assets/icons/user.png',
        selectedIconPath: './assets/icons/user-active.png',
      },
    ],
  },
})
