const buildProductKey = process.env.TARO_APP_PRODUCT_KEY || 'general'
const buildProductTabs = {
  general: [
    ['pages/today/index', '今日'],
    ['pages/index/index', '学习'],
    ['pages/question/index', '练习'],
    ['pages/user/index', '我的'],
  ],
  shenlun: [
    ['pages/rmrb/index', '今日'],
    ['pages/rmrb/article-list', '精读'],
    ['pages/rmrb/drill', '训练'],
    ['pages/user/index', '我的'],
  ],
  theory: [
    ['pages/theory/index', '今日'],
    ['pages/index/index', '专题'],
    ['pages/question/index', '刷题'],
    ['pages/user/index', '我的'],
  ],
}[buildProductKey] || [
  ['pages/today/index', '今日'],
  ['pages/index/index', '学习'],
  ['pages/question/index', '练习'],
  ['pages/user/index', '我的'],
]

export default defineAppConfig({
  pages: [
    'pages/auth/login',
    'pages/auth/register',
    'pages/today/index',
    'pages/index/index',
    'pages/article/detail',
    'pages/article/mindmap',
    'pages/question/index',
    'pages/question/taking',
    'pages/question/article-pick',
    'pages/question/review',
    'pages/question/wrong',
    'pages/question/manual-list',
    'pages/question/manual-quiz',
    'pages/question/manual-edit',
    'pages/user/index',
    'pages/user/profile',
    'pages/user/signin',
    'pages/user/points',
    'pages/user/rank',
    'pages/user/growth',
    'pages/user/feedback',
    'pages/user/data',
    'pages/corpus/index',
    'pages/corpus/edit',
    'pages/plan/today',
    'pages/plan/review',
    'pages/plan/week',
    'pages/plan/day',
    'pages/knowledge/index',
    'pages/events/index',
    'pages/events/edit',
    'pages/review/hub',
    'pages/review/quiz',
    'pages/exam/list',
    'pages/exam/detail',
    'pages/exam/taking',
    'pages/exam/result',
    'pages/ziliao/index',
    'pages/ziliao/formulas',
    'pages/ziliao/formula-detail',
    'pages/ziliao/types',
    'pages/ziliao/type-detail',
    'pages/ziliao/tricks',
    'pages/ziliao/trick-detail',
    'pages/ziliao/drill',
    'pages/ziliao/result',
    'pages/rmrb/index',
    'pages/rmrb/article-list',
    'pages/rmrb/article-detail',
    'pages/rmrb/mines',
    'pages/rmrb/mine-edit',
    'pages/rmrb/terms',
    'pages/rmrb/drill',
    'pages/shenlun/training',
    'pages/theory/index',
    'pages/theory/pack',
    'pages/theory/review',
  ],
  window: {
    navigationBarBackgroundColor: '#D0021B',
    navigationBarTitleText: '知行公考',
    navigationBarTextStyle: 'white',
    backgroundColor: '#F3F4F6',
  },
  tabBar: {
    color: '#999999',
    selectedColor: buildProductKey === 'theory' ? '#1E3A5F' : '#D0021B',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      // H5 开发态会误删 iconPath 首字符（assets → ssets），必须写 ./ 前缀；
      // 生产构建会自动改写并打包到 /static/images/*.png
      {
        pagePath: buildProductTabs[0][0],
        text: buildProductTabs[0][1],
        iconPath: './assets/icons/today.png',
        selectedIconPath: './assets/icons/today-active.png',
      },
      {
        pagePath: buildProductTabs[1][0],
        text: buildProductTabs[1][1],
        iconPath: './assets/icons/home.png',
        selectedIconPath: './assets/icons/home-active.png',
      },
      {
        pagePath: buildProductTabs[2][0],
        text: buildProductTabs[2][1],
        iconPath: './assets/icons/quiz.png',
        selectedIconPath: './assets/icons/quiz-active.png',
      },
      {
        pagePath: buildProductTabs[3][0],
        text: buildProductTabs[3][1],
        iconPath: './assets/icons/user.png',
        selectedIconPath: './assets/icons/user-active.png',
      },
    ],
  },
})
